export type TemplateCompetency = {
  code: string;
  name: string;
  description: string;
};

export type TemplateOption = {
  text: string;
  impacts: string;
};

export type TemplateQuestion = {
  code: string;
  sectionTitle: string;
  sectionKind: "PERSONALITY" | "SCENARIO";
  type: "LIKERT_TRAIT" | "SJT_SINGLE";
  category: string;
  prompt: string;
  trait: string;
  reverse: boolean;
  scaleMin: number;
  scaleMax: number;
  options: TemplateOption[];
};

export type RecommendedTemplate = {
  title: string;
  competencies: TemplateCompetency[];
  questions: TemplateQuestion[];
};

export const recommendedTemplate40: RecommendedTemplate = {
  title: "Corporate Workstyle & Personality 40",
  competencies: [
    {
      code: "emotional_intelligence",
      name: "Emotional Intelligence",
      description: "Recognizes emotions and responds constructively.",
    },
    {
      code: "collaboration",
      name: "Collaboration",
      description: "Builds trust and works effectively with others.",
    },
    {
      code: "adaptability",
      name: "Adaptability",
      description: "Adjusts quickly and productively to change.",
    },
    {
      code: "accountability",
      name: "Accountability",
      description: "Owns outcomes and follows through on commitments.",
    },
    {
      code: "communication",
      name: "Communication",
      description: "Shares information clearly and with audience awareness.",
    },
    {
      code: "conflict_management",
      name: "Conflict Management",
      description: "Handles disagreements constructively and fairly.",
    },
    {
      code: "learning_agility",
      name: "Learning Agility",
      description: "Learns quickly from experience and feedback.",
    },
    {
      code: "leadership_presence",
      name: "Leadership Presence",
      description: "Guides others with calm influence and clarity.",
    },
  ],
  questions: [
    {
      code: "p_open_1",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Openness",
      prompt: "I seek feedback that challenges my existing assumptions.",
      trait: "openness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_open_2",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Openness",
      prompt: "I enjoy learning tools and ideas outside my primary role.",
      trait: "openness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_open_3",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Openness",
      prompt: "I prefer established routines over trying unfamiliar approaches.",
      trait: "openness",
      reverse: true,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_open_4",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Openness",
      prompt: "I often connect ideas from unrelated domains to solve problems.",
      trait: "openness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_open_5",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Openness",
      prompt: "I volunteer for projects with unclear paths when they offer learning.",
      trait: "openness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_cons_1",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Conscientiousness",
      prompt: "I break complex goals into milestones and track progress.",
      trait: "conscientiousness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_cons_2",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Conscientiousness",
      prompt: "I keep commitments even when priorities become difficult.",
      trait: "conscientiousness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_cons_3",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Conscientiousness",
      prompt: "I delay difficult tasks until deadlines are close.",
      trait: "conscientiousness",
      reverse: true,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_cons_4",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Conscientiousness",
      prompt: "I maintain organized documentation others can easily follow.",
      trait: "conscientiousness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_cons_5",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Conscientiousness",
      prompt: "I perform quality checks before submitting work.",
      trait: "conscientiousness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_extra_1",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Extraversion",
      prompt: "I initiate discussion in cross-functional meetings.",
      trait: "extraversion",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_extra_2",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Extraversion",
      prompt: "Collaborative sessions increase my energy.",
      trait: "extraversion",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_extra_3",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Extraversion",
      prompt: "I avoid speaking unless someone asks me directly.",
      trait: "extraversion",
      reverse: true,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_extra_4",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Extraversion",
      prompt: "I build new professional relationships quickly.",
      trait: "extraversion",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_extra_5",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Extraversion",
      prompt: "I advocate for ideas confidently in group settings.",
      trait: "extraversion",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_agree_1",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Agreeableness",
      prompt: "I consider others constraints before pushing my own plan.",
      trait: "agreeableness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_agree_2",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Agreeableness",
      prompt: "I offer support when teammates are overloaded.",
      trait: "agreeableness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_agree_3",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Agreeableness",
      prompt: "I dismiss opposing viewpoints too quickly.",
      trait: "agreeableness",
      reverse: true,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_agree_4",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Agreeableness",
      prompt: "I resolve misunderstandings respectfully.",
      trait: "agreeableness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_agree_5",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Agreeableness",
      prompt: "I share credit for team achievements.",
      trait: "agreeableness",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_neuro_1",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Emotional Stability",
      prompt: "Unexpected changes make me feel anxious.",
      trait: "neuroticism",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_neuro_2",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Emotional Stability",
      prompt: "I dwell on small mistakes for longer than necessary.",
      trait: "neuroticism",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_neuro_3",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Emotional Stability",
      prompt: "I stay calm in high-pressure situations.",
      trait: "neuroticism",
      reverse: true,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_neuro_4",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Emotional Stability",
      prompt: "Critical feedback affects my focus for the rest of the day.",
      trait: "neuroticism",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "p_neuro_5",
      sectionTitle: "Personality Profile",
      sectionKind: "PERSONALITY",
      type: "LIKERT_TRAIT",
      category: "Emotional Stability",
      prompt: "I recover quickly after setbacks.",
      trait: "neuroticism",
      reverse: true,
      scaleMin: 1,
      scaleMax: 5,
      options: [],
    },
    {
      code: "s_ei_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Emotional Intelligence",
      prompt: "A teammate says they are emotionally distressed before a deadline. What do you do first?",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Acknowledge their stress, listen briefly, and connect them to support while adjusting task load.", impacts: "emotional_intelligence:+2,collaboration:+1,leadership_presence:+1" },
        { text: "Tell them to stay focused and discuss feelings after delivery.", impacts: "emotional_intelligence:-1,collaboration:-1,accountability:+1" },
        { text: "Escalate immediately without speaking to them further.", impacts: "emotional_intelligence:-1,communication:-1,accountability:+1" },
        { text: "Ignore it and continue with your own priorities.", impacts: "emotional_intelligence:-2,collaboration:-2" },
      ],
    },
    {
      code: "s_collab_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Collaboration",
      prompt: "Two teams disagree on ownership and delivery stalls. Your best response is:",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Facilitate a short alignment session with decision criteria and clear ownership.", impacts: "collaboration:+2,conflict_management:+2,communication:+1" },
        { text: "Ask each team to continue independently and compare outcomes later.", impacts: "adaptability:+1,collaboration:-1,accountability:-1" },
        { text: "Choose a side quickly to move faster.", impacts: "leadership_presence:+1,collaboration:-2,conflict_management:-1" },
        { text: "Wait for leadership intervention before doing anything.", impacts: "accountability:-1,leadership_presence:-1" },
      ],
    },
    {
      code: "s_adapt_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Adaptability",
      prompt: "A major requirement changes mid-sprint. What should you do first?",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Reassess scope with stakeholders, re-prioritize, and communicate tradeoffs clearly.", impacts: "adaptability:+2,communication:+1,accountability:+1" },
        { text: "Keep current scope and hope the change can fit without adjustments.", impacts: "adaptability:-2,accountability:-1" },
        { text: "Pause all work until complete clarity arrives.", impacts: "adaptability:-1,accountability:-1" },
        { text: "Push change fully without checking impact on deadlines.", impacts: "adaptability:+1,accountability:-2,communication:-1" },
      ],
    },
    {
      code: "s_account_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Accountability",
      prompt: "You realize your error may delay a release. You should:",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Inform stakeholders early, propose mitigation, and own the recovery plan.", impacts: "accountability:+2,communication:+1,leadership_presence:+1" },
        { text: "Fix quietly first and mention only if asked.", impacts: "accountability:-1,communication:-2" },
        { text: "Blame ambiguous requirements and request timeline extension.", impacts: "accountability:-2,collaboration:-1" },
        { text: "Hand off the issue to someone more experienced.", impacts: "accountability:-1,learning_agility:-1" },
      ],
    },
    {
      code: "s_comm_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Communication",
      prompt: "An executive asks for a status update with little time. Your response is:",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Provide a concise summary: current status, risk, and next action with owner/date.", impacts: "communication:+2,leadership_presence:+1,accountability:+1" },
        { text: "Share all details to avoid missing anything.", impacts: "communication:-1,accountability:+1" },
        { text: "Give optimistic estimates without mentioning risks.", impacts: "communication:-2,accountability:-1" },
        { text: "Delay response until a full deck is ready.", impacts: "communication:-1,adaptability:-1" },
      ],
    },
    {
      code: "s_conflict_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Conflict Management",
      prompt: "A colleague publicly criticizes your idea in a meeting. Best immediate reaction:",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Stay composed, clarify intent, and invite concrete alternatives.", impacts: "conflict_management:+2,emotional_intelligence:+1,communication:+1" },
        { text: "Respond sharply to defend your credibility.", impacts: "conflict_management:-2,emotional_intelligence:-1" },
        { text: "Withdraw from discussion and follow up later only by email.", impacts: "communication:-1,leadership_presence:-1" },
        { text: "Escalate immediately to their manager.", impacts: "conflict_management:-1,accountability:-1" },
      ],
    },
    {
      code: "s_learning_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Learning Agility",
      prompt: "You are assigned a new domain with tight timelines. What is your best approach?",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Identify critical knowledge gaps, seek mentors, and run rapid learning sprints.", impacts: "learning_agility:+2,adaptability:+1,accountability:+1" },
        { text: "Work as usual and learn only if issues appear.", impacts: "learning_agility:-2,adaptability:-1" },
        { text: "Refuse task until formal training is completed.", impacts: "learning_agility:-1,adaptability:-1" },
        { text: "Rely entirely on one teammate for direction.", impacts: "learning_agility:-1,accountability:-1,collaboration:+1" },
      ],
    },
    {
      code: "s_lead_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Leadership Presence",
      prompt: "During a high-visibility incident, people seem confused. You should:",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Define immediate priorities, assign owners, and communicate update cadence.", impacts: "leadership_presence:+2,communication:+1,accountability:+1" },
        { text: "Wait for someone senior to coordinate response.", impacts: "leadership_presence:-2,accountability:-1" },
        { text: "Ask everyone to work independently and report when done.", impacts: "leadership_presence:-1,collaboration:-1" },
        { text: "Focus only on your component and avoid broader coordination.", impacts: "leadership_presence:-1,collaboration:-1,accountability:+1" },
      ],
    },
    {
      code: "s_feedback_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Feedback Receptivity",
      prompt: "You receive tough feedback that your communication is unclear.",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Ask for examples, summarize learning, and test a clearer communication format.", impacts: "learning_agility:+2,communication:+1,emotional_intelligence:+1" },
        { text: "Defend your style and explain why feedback is unfair.", impacts: "learning_agility:-2,emotional_intelligence:-1" },
        { text: "Acknowledge feedback but make no change.", impacts: "learning_agility:-1,accountability:-1" },
        { text: "Avoid future conversations with the person giving feedback.", impacts: "collaboration:-1,conflict_management:-1" },
      ],
    },
    {
      code: "s_delegate_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Delegation",
      prompt: "You are overloaded and a deadline is close. What is the best move?",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Prioritize outcomes, delegate clear tasks, and set check-in points.", impacts: "leadership_presence:+1,accountability:+1,communication:+1,collaboration:+1" },
        { text: "Do everything yourself to ensure quality.", impacts: "accountability:+1,collaboration:-1,adaptability:-1" },
        { text: "Delegate without context and expect people to figure it out.", impacts: "communication:-2,accountability:-1" },
        { text: "Request deadline extension immediately without exploring alternatives.", impacts: "adaptability:-1,accountability:-1" },
      ],
    },
    {
      code: "s_prioritize_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Prioritization",
      prompt: "You have three urgent requests from different stakeholders. You should:",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Clarify impact/urgency, align priorities transparently, and communicate sequence.", impacts: "accountability:+2,communication:+1,leadership_presence:+1" },
        { text: "Start whichever request came first.", impacts: "accountability:-1,adaptability:-1" },
        { text: "Pick the request from the most senior stakeholder only.", impacts: "communication:-1,collaboration:-1" },
        { text: "Try to do all three simultaneously with no prioritization.", impacts: "accountability:-2,adaptability:-1" },
      ],
    },
    {
      code: "s_ethics_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Integrity",
      prompt: "You notice a metric is being reported in a misleading way. What do you do?",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Raise concern with evidence and propose transparent correction.", impacts: "accountability:+2,leadership_presence:+1,communication:+1" },
        { text: "Stay silent because results look positive.", impacts: "accountability:-2" },
        { text: "Privately tell a colleague but take no action.", impacts: "accountability:-1,communication:-1" },
        { text: "Publicly accuse someone before checking context.", impacts: "conflict_management:-1,communication:-1" },
      ],
    },
    {
      code: "s_remote_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Remote Collaboration",
      prompt: "A remote teammate has gone quiet and is missing updates. Your first move is:",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Reach out directly, clarify blockers, and agree on a support plan.", impacts: "collaboration:+2,emotional_intelligence:+1,communication:+1" },
        { text: "Complain in team channel about responsiveness.", impacts: "collaboration:-2,communication:-1" },
        { text: "Reassign their work without telling them.", impacts: "communication:-1,accountability:+1,collaboration:-1" },
        { text: "Ignore it and wait for next standup.", impacts: "accountability:-1,collaboration:-1" },
      ],
    },
    {
      code: "s_innovation_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Innovation",
      prompt: "A junior teammate proposes an unconventional idea with potential upside. You should:",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Run a small experiment with clear success criteria.", impacts: "learning_agility:+1,adaptability:+1,leadership_presence:+1" },
        { text: "Reject it because it differs from current approach.", impacts: "learning_agility:-2,adaptability:-1" },
        { text: "Approve full rollout immediately without validation.", impacts: "adaptability:+1,accountability:-2" },
        { text: "Delay discussion indefinitely.", impacts: "learning_agility:-1,communication:-1" },
      ],
    },
    {
      code: "s_crossculture_1",
      sectionTitle: "Workplace Scenarios",
      sectionKind: "SCENARIO",
      type: "SJT_SINGLE",
      category: "Inclusive Collaboration",
      prompt: "In a global meeting, one location dominates discussion while others are silent.",
      trait: "",
      reverse: false,
      scaleMin: 1,
      scaleMax: 5,
      options: [
        { text: "Facilitate turn-taking and invite quieter voices intentionally.", impacts: "collaboration:+2,communication:+1,leadership_presence:+1" },
        { text: "Continue with dominant speakers to save time.", impacts: "collaboration:-2" },
        { text: "Move discussion offline with only senior participants.", impacts: "collaboration:-1,communication:-1" },
        { text: "End meeting early and postpone decisions.", impacts: "accountability:-1,leadership_presence:-1" },
      ],
    },
  ],
};
